In [13]:
import pandas as pd
# cv , baseline, feature

In [14]:
train = pd.read_csv('./train_job/train.csv')

In [15]:
test = pd.read_csv('./test_job.csv')

In [16]:
sample_output_job=  pd.read_csv('./sample_output_job.csv')

In [17]:
job_tag = pd.read_csv('./train_job/job_tags.csv')

In [18]:
job_companies = pd.read_csv('./train_job/job_companies.csv')

In [19]:
tags = pd.read_csv('./train_job/tags.csv')

In [20]:
user_tags = pd.read_csv('./train_job/user_tags.csv')

In [21]:
tags

tagID                   keyword
0    602d1305678a8d5fdb372271e980da6a  Amazon Web Services(AWS)
1    e3251075554389fe91d17a794861d47b                Tensorflow
2    a1d50185e7426cbb0acad1e6ca74b9aa                    Docker
3    884d79963bd8bc0ae9b13a1aa71add73                       Git
4    4122cb13c7a474c1976c9706ae36521d                    Python
..                                ...                       ...
882  818f4654ed39a1c147d1e51a00ffb4cb                        활용
883  7cce53cf90577442771720a370c3c723                    mybais
884  c2aee86157b4a40b78132f1e71a9e6f1                         *
885  1fb2a1c37b18aa4611c3949d6148d0f8             Autodesk Maya
886  5fa9e41bfec0725742cc9d15ef594120                Apache Pig

[887 rows x 2 columns]

In [22]:
job_tag.merge(tags, on='tagID', how='left')

jobID                             tagID  \
0     320722549d1751cf3f247855f937b982  d38901788c533e8286cb6400b40b386d   
1     e744f91c29ec99f0e662c9177946c627  3948ead63a9f2944218de038d8934305   
2     e744f91c29ec99f0e662c9177946c627  0e095e054ee94774d6a496099eb1cf6a   
3     e820a45f1dfc7b95282d10b6087e11c0  7d771e0e8f3633ab54856925ecdefc5d   
4     e820a45f1dfc7b95282d10b6087e11c0  6c8dba7d0df1c4a79dd07646be9a26c8   
...                                ...                               ...   
3472  b4a528955b84f584974e92d025a75d1f  bb04af0f7ecaee4aae62035497da1387   
3473  6c8dba7d0df1c4a79dd07646be9a26c8  3bf55bbad370a8fcad1d09b005e278c2   
3474  6c8dba7d0df1c4a79dd07646be9a26c8  0e9fa1f3e9e66792401a6972d477dcc3   
3475  6c8dba7d0df1c4a79dd07646be9a26c8  0c048b3a434e49e655c1247efb389cec   
3476  9f36407ead0629fc166f14dde7970f68  c4851e8e264415c4094e4e85b0baa7cc   

         keyword  
0           Ruby  
1        Node.js  
2     JavaScript  
3           HTML  
4         Vue.js  
...          ...  
3472         C++  
3473       Swift  
3474       Realm  
3475    Firebase  
3476         PHP  

[3477 rows x 3 columns]

In [23]:
import numpy as np
np.empty(shape=(0,1782))


array([], shape=(0, 1782), dtype=float64)

In [24]:
train['userID'].unique()

array(['fe292163d06253b716e9a0099b42031d',
       '6377fa90618fae77571e8dc90d98d409',
       '8ec0888a5b04139be0dfe942c7eb4199',
       'f862b39f767d3a1991bdeb2ea1401c9c',
       'cac14930c65d72c16efac2c51a6b7f71',
       'ed1ca6971578b1da0e4ad55b48d77fda',
       '8109c2c482264f96f8ac69a9a99db308',
       '14ccd7a3d2daa57d06f4741f0168bb1d',
       '2afacaaf807c1843c41896ae794835d9',
       'd7b2c4284fda91263ab9b89254cd7c43',
       '8ec72a61b2adad097a1c3aa06751e8c4',
       '6da6479250104018131de61655f1f385',
       '4952d2ac78b534c78d7a21c60a236e4c',
       '838c13b8aa97e2d988ef4495460f2e0e',
       '2f05776d37d873642af484255572600d',
       '40369b31ac85b623b72c3d50151ff55c',
       'd41e0e6f6f1e29098d9d152511503ab2',
       '879b56cccf6b57314ad724c65cf270e9',
       'b3c865b84617fa5e555865ebe0e54612',
       'b052e2e0c0ad1b2d5036bd56e27d061c',
       'a35af76a1c0bb174a3cfc66592804848',
       'c70daf247944fe3add32218f914c75a6',
       'cb08b2c94dbb772324444bb4ed7cc1a4',
       'e75

In [25]:
job_tag['jobID'].unique()

array(['320722549d1751cf3f247855f937b982',
       'e744f91c29ec99f0e662c9177946c627',
       'e820a45f1dfc7b95282d10b6087e11c0',
       '53c3bce66e43be4f209556518c2fcb54',
       'fd06b8ea02fe5b1c2496fe1700e9d16c',
       '6e7d2da6d3953058db75714ac400b584',
       '818f4654ed39a1c147d1e51a00ffb4cb',
       '019d385eb67632a7e958e23f24bd07d7',
       '8757150decbd89b0f5442ca3db4d0e0e',
       '3871bd64012152bfb53fdf04b401193f',
       '1651cf0d2f737d7adeab84d339dbabd3',
       '7f975a56c761db6506eca0b37ce6ec87',
       '66808e327dc79d135ba18e051673d906',
       '50c3d7614917b24303ee6a220679dab3',
       '884ce4bb65d328ecb03c598409e2b168',
       'b5b41fac0361d157d9673ecb926af5ae',
       'ce5140df15d046a66883807d18d0264b',
       '96b9bff013acedfb1d140579e2fbeb63',
       'dc912a253d1e9ba40e2c597ed2376640',
       '24146db4eb48c718b84cae0a0799dcfc',
       'a8ecbabae151abacba7dbde04f761c37',
       'c60d060b946d6dd6145dcbad5c4ccf6f',
       'e5e63da79fcd2bebbd7cb8bf1c1d0274',
       '15d

In [26]:
job_companies['companySize'].unique()

array([nan, '11-50', '101-200', '1-10', '51-100', '1000 이상', '201-500',
       '501-1000'], dtype=object)

In [27]:
# text 정보를 input 으로 주자
# user를 latent factor로 만들고?
train.merge(tags, '')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [29]:
tags

tagID                   keyword
0    602d1305678a8d5fdb372271e980da6a  Amazon Web Services(AWS)
1    e3251075554389fe91d17a794861d47b                Tensorflow
2    a1d50185e7426cbb0acad1e6ca74b9aa                    Docker
3    884d79963bd8bc0ae9b13a1aa71add73                       Git
4    4122cb13c7a474c1976c9706ae36521d                    Python
..                                ...                       ...
882  818f4654ed39a1c147d1e51a00ffb4cb                        활용
883  7cce53cf90577442771720a370c3c723                    mybais
884  c2aee86157b4a40b78132f1e71a9e6f1                         *
885  1fb2a1c37b18aa4611c3949d6148d0f8             Autodesk Maya
886  5fa9e41bfec0725742cc9d15ef594120                Apache Pig

[887 rows x 2 columns]

In [33]:

job_tag = job_tag.merge(tags, on='tagID', how='left')

In [43]:

job_tag.groupby(['keyword'])

jobID                             tagID  \
0     320722549d1751cf3f247855f937b982  d38901788c533e8286cb6400b40b386d   
1     e744f91c29ec99f0e662c9177946c627  3948ead63a9f2944218de038d8934305   
2     e744f91c29ec99f0e662c9177946c627  0e095e054ee94774d6a496099eb1cf6a   
3     e820a45f1dfc7b95282d10b6087e11c0  7d771e0e8f3633ab54856925ecdefc5d   
4     e820a45f1dfc7b95282d10b6087e11c0  6c8dba7d0df1c4a79dd07646be9a26c8   
...                                ...                               ...   
3472  b4a528955b84f584974e92d025a75d1f  bb04af0f7ecaee4aae62035497da1387   
3473  6c8dba7d0df1c4a79dd07646be9a26c8  3bf55bbad370a8fcad1d09b005e278c2   
3474  6c8dba7d0df1c4a79dd07646be9a26c8  0e9fa1f3e9e66792401a6972d477dcc3   
3475  6c8dba7d0df1c4a79dd07646be9a26c8  0c048b3a434e49e655c1247efb389cec   
3476  9f36407ead0629fc166f14dde7970f68  c4851e8e264415c4094e4e85b0baa7cc   

         keyword  
0           Ruby  
1        Node.js  
2     JavaScript  
3           HTML  
4         Vue.js  
...          ...  
3472         C++  
3473       Swift  
3474       Realm  
3475    Firebase  
3476         PHP  

[3477 rows x 3 columns]

In [45]:
job_tag_grp = job_tag.groupby('jobID')

In [56]:
for job_grp in job_tag_grp:
    keywords = ' '.join(job_grp[1]['keyword'].values)
    job_tag.loc[job_tag.jobID ==job_grp[0],'keywords'] = keywords
    break


In [ ]:
# generate grp
# 가독성 좋은 코드로
#
user_tags_merge_grp = user_tags_merge.groupby('userID')
# 도메인 지식으로 frontend라고 구분지어도되나
for user_grp in user_tags_merge_grp:
    print(user_grp)
    # 관심사 키워드 유니크값만
    interest_keyword = ' '.join(user_grp[1]['keyword'].unique())
    user_tags.loc[user_tags.userID ==user_grp[0],'interest_keyword'] = interest_keyword

In [67]:
tags_index_dict = dict()
for i in range(0, len(tags)):
    tags_index_dict[tags["tagID"][i]] = i


In [71]:
size_dict = {"1-10": 1, "11-50": 2, "51-100": 3, "101-200": 4, "201-500": 5, "501-1000": 6, "1000 이상": 7}
a = 1
for k, v in size_dict.items():
    m = np.zeros(shape=(8))
    m[a] = 1.
    size_dict[k] = m
    a += 1

{'1-10': array([0., 1., 0., 0., 0., 0., 0., 0.]),
 '11-50': array([0., 0., 1., 0., 0., 0., 0., 0.]),
 '51-100': array([0., 0., 0., 1., 0., 0., 0., 0.]),
 '101-200': array([0., 0., 0., 0., 1., 0., 0., 0.]),
 '201-500': array([0., 0., 0., 0., 0., 1., 0., 0.]),
 '501-1000': array([0., 0., 0., 0., 0., 0., 1., 0.]),
 '1000 이상': array([0., 0., 0., 0., 0., 0., 0., 1.])}

In [74]:
jobs = data_companies
company_one_hot = dict()
for i in range(0, len(jobs)):
    id = jobs["jobID"][i]
    size = jobs["companySize"][i]
    if size not in size_dict:
        size = np.zeros(shape=(8))
        size[0] = 1.
    else:
        size = size_dict[jobs["companySize"][i]]
    company_one_hot[id] = size

In [77]:
len(company_one_hot.keys())

733

In [70]:
len(tags_index_dict.keys())

887

In [78]:
users =data_user_tag
index = 'userID'
users_tags_dict= dict()
for i in range(0, len(users)):
    first = users[index][i]
    tagID = users["tagID"][i]

    if first not in users_tags_dict:
        users_tags_dict[first] = [tagID]
    else:
        k = users_tags_dict[first]
        k.append(tagID)
        users_tags_dict[first] = k

In [82]:
len(users_tags_dict.keys())

196

In [83]:
users =data_jobs
index = 'jobID'
users_tags_dict= dict()
for i in range(0, len(users)):
    first = users[index][i]
    tagID = users["tagID"][i]

    if first not in users_tags_dict:
        users_tags_dict[first] = [tagID]
    else:
        k = users_tags_dict[first]
        k.append(tagID)
        users_tags_dict[first] = k

In [85]:
len(users_tags_dict.keys())

733

In [ ]:
id_one_hot = dict()
for key, values in users_tags_dict.items():
    # one_hot = [0 for i in range(0, len(tags_index_dict))]
    one_hot = np.zeros(shape=(len(tags_index_dict)))
    for v in values:
        one_hot[tags_index_dict[v]] = 1.
    id_one_hot[key] = one_hot

In [1]:
import pandas as pd
import numpy as np

def tags_to_one_hot(tags):
    # tag to index
    tags_index_dict = dict()
    for i in range(0, len(tags)):
        tags_index_dict[tags["tagID"][i]] = i
    return tags_index_dict

def jobs_company_to_one_hot(jobs):
    # size to one hot
    size_dict = {"1-10": 1, "11-50": 2, "51-100": 3, "101-200": 4, "201-500": 5, "501-1000": 6, "1000 이상": 7}
    a = 1
    for k, v in size_dict.items():
        m = np.zeros(shape=(8))
        m[a] = 1.
        size_dict[k] = m
        a += 1

    # jobs to one hot
    company_one_hot = dict()
    for i in range(0, len(jobs)):
        id = jobs["jobID"][i]
        size = jobs["companySize"][i]
        if size not in size_dict:
            size = np.zeros(shape=(8))
            size[0] = 1.
        else:
            size = size_dict[jobs["companySize"][i]]
        company_one_hot[id] = size
    return company_one_hot

def id_to_one_hot(tags_index_dict, users, index):
    # ids to tag dic
    users_tags_dict= dict()
    for i in range(0, len(users)):
        first = users[index][i]
        tagID = users["tagID"][i]

        if first not in users_tags_dict:
            users_tags_dict[first] = [tagID]
        else:
            k = users_tags_dict[first]
            k.append(tagID)
            users_tags_dict[first] = k

    # ids to tag one hot
    id_one_hot = dict()
    for key, values in users_tags_dict.items():
        # one_hot = [0 for i in range(0, len(tags_index_dict))]
        one_hot = np.zeros(shape=(len(tags_index_dict)))
        for v in values:
            one_hot[tags_index_dict[v]] = 1.
        id_one_hot[key] = one_hot
    return id_one_hot

data_train = pd.read_csv("./train_job/train.csv")
data_user_tag = pd.read_csv("./train_job/user_tags.csv")
data_tags = pd.read_csv("./train_job/tags.csv")
data_jobs = pd.read_csv("./train_job/job_tags.csv")
data_companies = pd.read_csv("./train_job/job_companies.csv")

tags_one_hot = tags_to_one_hot(data_tags)
users_one_hot = id_to_one_hot(tags_one_hot, data_user_tag, "userID")
jobs_one_hot = id_to_one_hot(tags_one_hot, data_jobs, "jobID")
company_one_hot = jobs_company_to_one_hot(data_companies)

X = np.empty(shape=(0,1782))
Y = np.asarray(data_train["applied"].tolist())
for i in range(0, len(data_train)):
    all = np.concatenate((users_one_hot[data_train["userID"][i]], jobs_one_hot[data_train["jobID"][i]], company_one_hot[data_train["jobID"][i]]), axis=0)
    X = np.append(X, np.array([all]), axis=0)
    break


In [ ]:
users_one_hot[data_train["userID"][i]]

In [59]:
X

array([[0., 0., 1., ..., 0., 0., 0.]])

In [ ]:
users_tags_dict= dict()
for i in range(0, len(users)):
    first = users[index][i]
    tagID = users["tagID"][i]

    if first not in users_tags_dict:
        users_tags_dict[first] = [tagID]
    else:
        k = users_tags_dict[first]
        k.append(tagID)
        users_tags_dict[first] = k

In [ ]:
# one-hot으로 input만들어설계한 모델


In [87]:
import pandas as pd
import numpy as np

def tags_to_one_hot(tags):
    # tag to index
    tags_index_dict = dict()
    for i in range(0, len(tags)):
        tags_index_dict[tags["tagID"][i]] = i
    return tags_index_dict

def jobs_company_to_one_hot(jobs):
    # size to one hot
    size_dict = {"1-10": 1, "11-50": 2, "51-100": 3, "101-200": 4, "201-500": 5, "501-1000": 6, "1000 이상": 7}
    a = 1
    for k, v in size_dict.items():
        m = np.zeros(shape=(8))
        m[a] = 1.
        size_dict[k] = m
        a += 1

    # jobs to one hot
    company_one_hot = dict()
    for i in range(0, len(jobs)):
        id = jobs["jobID"][i]
        size = jobs["companySize"][i]
        if size not in size_dict:
            size = np.zeros(shape=(8))
            size[0] = 1.
        else:
            size = size_dict[jobs["companySize"][i]]
        company_one_hot[id] = size
    return company_one_hot

def id_to_one_hot(tags_index_dict, users, index):
    # ids to tag dic
    users_tags_dict= dict()
    for i in range(0, len(users)):
        first = users[index][i]
        tagID = users["tagID"][i]

        if first not in users_tags_dict:
            users_tags_dict[first] = [tagID]
        else:
            k = users_tags_dict[first]
            k.append(tagID)
            users_tags_dict[first] = k

    # ids to tag one hot
    id_one_hot = dict()
    for key, values in users_tags_dict.items():
        # one_hot = [0 for i in range(0, len(tags_index_dict))]
        one_hot = np.zeros(shape=(len(tags_index_dict)))
        for v in values:
            one_hot[tags_index_dict[v]] = 1.
        id_one_hot[key] = one_hot
    return id_one_hot

data_train = pd.read_csv("./train_job/train.csv")
data_user_tag = pd.read_csv("./train_job/user_tags.csv")
data_tags = pd.read_csv("./train_job/tags.csv")
data_jobs = pd.read_csv("./train_job/job_tags.csv")
data_companies = pd.read_csv("./train_job/job_companies.csv")

tags_one_hot = tags_to_one_hot(data_tags)
users_one_hot = id_to_one_hot(tags_one_hot, data_user_tag, "userID")
jobs_one_hot = id_to_one_hot(tags_one_hot, data_jobs, "jobID")
company_one_hot = jobs_company_to_one_hot(data_companies)

X = np.empty(shape=(0,1782))
Y = np.asarray(data_train["applied"].tolist())
for i in range(0, len(data_train)):
    all = np.concatenate((users_one_hot[data_train["userID"][i]], jobs_one_hot[data_train["jobID"][i]], company_one_hot[data_train["jobID"][i]]), axis=0)
    X = np.append(X, np.array([all]), axis=0)



KeyboardInterrupt



In [98]:
users_tags_dict= dict()
for i in range(0, len(users)):
    first = users[index][i]
    tagID = users["tagID"][i]

    if first not in users_tags_dict:
        users_tags_dict[first] = [tagID]
    else:
        k = users_tags_dict[first]
        k.append(tagID)
        users_tags_dict[first] = k

# ids to tag one hot
id_one_hot = dict()
for key, values in users_tags_dict.items():
    # one_hot = [0 for i in range(0, len(tags_index_dict))]
    one_hot = np.zeros(shape=(len(tags_index_dict)))
    for v in values:
        one_hot[tags_index_dict[v]] = 1.
    id_one_hot[key] = one_hot

In [107]:
len(users_one_hot[data_train["userID"][i]])

887

In [111]:
len(id_to_one_hot(tags_one_hot, data_user_tag, "userID"))

196

In [110]:
len( id_to_one_hot(tags_one_hot, data_jobs, "jobID"))

733

In [102]:
len(users_tags_dict.keys())

733

In [97]:
887*2 +7

1781

In [90]:
len(users_tags_dict.keys())

733

In [96]:
company_one_hot[data_train["jobID"][i]]

array([0., 0., 0., 1., 0., 0., 0., 0.])

In [95]:
jobs_one_hot[data_train["jobID"][i]]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [91]:
user_tags['userID'].unique()

array(['e576423831e043f7928d9ac113abbe6f',
       '3532ee676d13916210e903ff4d85c04f',
       '3203e06c1efc6fdb23016650d1d1888c',
       '4952d2ac78b534c78d7a21c60a236e4c',
       '788ecdd13f033f8131eecd90ee59993e',
       '3f616e2b4d8527b9ce80f20268fd82c0',
       'ab33d7af928bc6bd6ef560d4b4081276',
       'd820bd12e2eec2ccc2403777eec0e025',
       '65f2e6f22b24b36f9fcb364dfafeee74',
       '6bd22a86b1f7a3a11de928d301f86d67',
       'ed1ca6971578b1da0e4ad55b48d77fda',
       'bf1752a1ae4e621b22d3ab7ae4ce0235',
       'eeedf6d4d717eba333e1b53f1b5375c8',
       '11bbe38e1cd8d806c2f4f372c7975642',
       'fdfa9a38cf3d8d850a6fd47b438bfe43',
       '11bd610a99ecb39c4be8335c6656ac19',
       'f32196295a6f0c13d5bedc880d3d66a2',
       '40369b31ac85b623b72c3d50151ff55c',
       '277d63d5ef81b08f2e59a74e82d53334',
       '849c1698afcec69d2ccf6ca24203c838',
       '87c0a904d6f959e5ecbd0bdaa29d8be9',
       '461beab646d4e7e0fd168125f577483b',
       'a35af76a1c0bb174a3cfc66592804848',
       '078

In [93]:
data_companies.companyID

0      00411460f7c92d2124a67ea0f4cb5f85
1      1905aedab9bf2477edc068a355bba31a
2      89fcd07f20b6785b92134bd6c1d0fa42
3      acf4b89d3d503d8252c9c4ba75ddbf6d
4      fb7b9ffa5462084c5f4e7e85a093e6d7
                     ...               
728    b5dc4e5d9b495d0196f61d45b26ef33e
729    2dace78f80bc92e6d7493423d729448e
730    443cb001c138b2561a0d90720d6ce111
731    b5b41fac0361d157d9673ecb926af5ae
732    64223ccf70bbb65a3a4aceac37e21016
Name: companyID, Length: 733, dtype: object

In [94]:
tags

tagID                   keyword
0    602d1305678a8d5fdb372271e980da6a  Amazon Web Services(AWS)
1    e3251075554389fe91d17a794861d47b                Tensorflow
2    a1d50185e7426cbb0acad1e6ca74b9aa                    Docker
3    884d79963bd8bc0ae9b13a1aa71add73                       Git
4    4122cb13c7a474c1976c9706ae36521d                    Python
..                                ...                       ...
882  818f4654ed39a1c147d1e51a00ffb4cb                        활용
883  7cce53cf90577442771720a370c3c723                    mybais
884  c2aee86157b4a40b78132f1e71a9e6f1                         *
885  1fb2a1c37b18aa4611c3949d6148d0f8             Autodesk Maya
886  5fa9e41bfec0725742cc9d15ef594120                Apache Pig

[887 rows x 2 columns]

In [88]:
users_one_hot[data_train["userID"][i]]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.